---
- name: Experiment with RACF group commands
  hosts: zoslab
  gather_facts: false

  environment: "{{ environment_vars }}"

  vars:
    racf_group:
      identity:
        name: D03GRP

      hierarchy:
        owner: GAMA18
        superior_group: SYS1

      omvs:
        gid: 8031

      installation_data: ""

      model_data_set: ""

      metadata:
        created: ""

      subgroups: []

      connected_users: []

  tasks:
    - name: Display RACF group definition
      ansible.builtin.debug:
        var: racf_group

    - name: Delete RACF group if it already exists
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "DELGROUP {{ racf_group.identity.name }}"
      ignore_errors: true

    - name: Create RACF group
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "ADDGROUP {{ racf_group.identity.name }} OWNER({{ racf_group.hierarchy.owner }}) SUPGROUP({{ racf_group.hierarchy.superior_group }}) OMVS(GID({{ racf_group.omvs.gid }}))"
      register: addgroup_result

    - name: Show ADDGROUP result
      ansible.builtin.debug:
        var: addgroup_result.output

    - name: Verify RACF group
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "LISTGRP {{ racf_group.identity.name }}"
      register: listgrp_result

    - name: Show LISTGRP result
      ansible.builtin.debug:
        var: listgrp_result.output

    - name: Extract created date
      ansible.builtin.set_fact:
        created_date: >-
          {{
            (listgrp_result.output[0].content | join(' '))
            | regex_search('CREATED=([0-9.]+)', '\1')
          }}

    - name: Display RACF information
      ansible.builtin.debug:
        msg:
          created: "{{ created_date }}"
          installation_data: "{{ racf_group.installation_data }}"
          subgroups: "{{ racf_group.subgroups }}"
          connected_users: "{{ racf_group.connected_users }}"

    - name: Delete RACF group
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "DELGROUP {{ racf_group.identity.name }}"
      register: delgroup_result

    - name: Show DELGROUP result
      ansible.builtin.debug:
        var: delgroup_result.output
